// @ts-nocheck
import { StyleSheet } from "react-native";
export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#0B0B0F" },
  screenContent: { padding: 16, gap: 12 },
  flex: { flex: 1 },
  col: { flexDirection: "column", gap: 8 },
  row: { flexDirection: "row", gap: 8, alignItems: "center" },
  text: { color: "#E5E7EB", fontSize: 15 },
  muted: { color: "#9CA3AF", fontSize: 13 },
  button: { backgroundColor: "#6366F1", paddingVertical: 12, paddingHorizontal: 16, borderRadius: 10, alignItems: "center" },
  buttonText: { color: "#fff", fontWeight: "600", fontSize: 15 },
  input: { borderWidth: 1, borderColor: "#2A2A35", borderRadius: 10, padding: 12, color: "#E5E7EB", backgroundColor: "#15151C" },
  textArea: { minHeight: 90, textAlignVertical: "top" },
  card: { backgroundColor: "#15151C", borderRadius: 12, padding: 14, borderWidth: 1, borderColor: "#23232E", gap: 8 },
  chip: { alignSelf: "flex-start", borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 3 },
  chipText: { fontSize: 12, fontWeight: "600" },
  table: { gap: 4 },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#23232E", paddingVertical: 8 },
  tableHead: { borderBottomWidth: 2 },
  tableHeadText: { color: "#9CA3AF", fontWeight: "700", fontSize: 12 },
  tableCell: { flex: 1, paddingHorizontal: 4 },
  tableCellText: { color: "#E5E7EB", fontSize: 13 },
  selectOption: { padding: 12, borderWidth: 1, borderColor: "#2A2A35", borderTopWidth: 0 },
  timelineItem: { flexDirection: "row", gap: 10, paddingVertical: 6 },
  timelineDot: { width: 12, height: 12, borderRadius: 6, marginTop: 4 },
  timelineTitle: { color: "#E5E7EB", fontSize: 15, fontWeight: "600" },
  imagePlaceholder: { backgroundColor: "#15151C", borderWidth: 1, borderColor: "#23232E", alignItems: "center", justifyContent: "center" },
  statCard: { backgroundColor: "#15151C", borderRadius: 12, padding: 14, borderWidth: 1, borderColor: "#23232E", gap: 4, minWidth: 120 },
  statValue: { color: "#E5E7EB", fontSize: 26, fontWeight: "700" },
});
