// ═══════════════════════════════════════════════════════════════
// Mint Runtime — Bundled JS library for exported apps
//
// This is the COMPILED runtime that ships inside exported projects.
// It provides state management, expression evaluation, action
// dispatch, and data binding — all framework-agnostic.
//
// Generated by: lib/convert/builders → injected into ZIP exports
//
// Used by:
//   - React Native (Expo) apps
//   - React (Vite) web apps
//   - Next.js apps
//   - Vue/Svelte apps (future)
// ═══════════════════════════════════════════════════════════════

export function generateMintRuntimeBundle(): string {
  return `// ═══════════════════════════════════════════════════════════════
// @mint/runtime — Embedded state, actions, expressions, bindings
// Auto-generated — do not edit manually
// ═══════════════════════════════════════════════════════════════

// ── Runtime config (backend origin + auth token) ──────────────
// configureMint() is called by the host (MintProvider) with the env-resolved
// API origin + project token, so relative backend calls (auth, fetch, DB)
// hit the right host with credentials instead of the app's own origin.
let _apiBase = "";
let _authToken = "";
let _storage = null;
let _projectId = "";
export function configureMint(opts) {
  if (!opts) return;
  if (opts.apiOrigin != null) _apiBase = String(opts.apiOrigin).replace(/\\/$/, "");
  if (opts.authToken != null) _authToken = String(opts.authToken);
  if (opts.storage != null) _storage = opts.storage;
  if (opts.projectId != null) _projectId = String(opts.projectId);
}
// Persisted session (end-user account + token). Note: managed-DB calls still
// authenticate with the baked project sync token — the server DML endpoint does
// not validate per-user tokens yet — so this is for session restore, not DB auth.
function _sessionKey() { return "mint:session:" + (_projectId || "app"); }
async function _persistSession(user, token) {
  if (!_storage) return;
  try { await _storage.setItem(_sessionKey(), JSON.stringify({ user: user, token: token })); } catch (e) {}
}
async function _clearSession() {
  if (!_storage) return;
  try { await _storage.removeItem(_sessionKey()); } catch (e) {}
}
// Restore { user, token } into runtime state on app startup. Call once on mount.
export async function hydrateSession(runtime, opts) {
  opts = opts || {};
  if (!_storage || !runtime || !runtime.state) return null;
  try {
    const raw = await _storage.getItem(_sessionKey());
    if (!raw) return null;
    const s = JSON.parse(raw);
    if (s && s.user) {
      runtime.state.set(opts.userPath || "user", s.user);
      if (s.token !== undefined) runtime.state.set(opts.tokenPath || "session.token", s.token);
    }
    return s;
  } catch (e) { return null; }
}
function _isAbsUrl(u) { return /^https?:\\/\\//.test(String(u)); }
function _resolveUrl(u) {
  const s = String(u);
  if (_isAbsUrl(s)) return s;
  if (!_apiBase) return s;
  return _apiBase + (s.charAt(0) === "/" ? s : "/" + s);
}
function _authHeaders(extra) {
  const h = Object.assign({}, extra || {});
  if (_authToken) h["Authorization"] = "Bearer " + _authToken;
  return h;
}

// ── Expression Parser ─────────────────────────────────────────

const MAX_DEPTH = 64;

function tokenize(source) {
  const tokens = [];
  let i = 0;
  while (i < source.length) {
    if (/\\s/.test(source[i])) { i++; continue; }
    const ch = source[i];
    const next = source[i + 1] || "";

    // State ref
    if (ch === "$") {
      const start = i; i++;
      let ref = "";
      while (i < source.length && /[a-zA-Z0-9_.]/.test(source[i])) { ref += source[i]; i++; }
      tokens.push({ type: "StateRef", value: ref, pos: start });
      continue;
    }
    // Numbers
    if (/[0-9]/.test(ch) || (ch === "." && /[0-9]/.test(next))) {
      let num = "";
      while (i < source.length && /[0-9.]/.test(source[i])) { num += source[i]; i++; }
      tokens.push({ type: "Number", value: num, pos: i });
      continue;
    }
    // Strings
    if (ch === "'" || ch === '"') {
      const q = ch; const start = i; i++;
      let str = "";
      while (i < source.length && source[i] !== q) {
        if (source[i] === "\\\\") { i++; str += source[i] || ""; } else { str += source[i]; }
        i++;
      }
      i++;
      tokens.push({ type: "String", value: str, pos: start });
      continue;
    }
    // Identifiers
    if (/[a-zA-Z_]/.test(ch)) {
      let id = "";
      while (i < source.length && /[a-zA-Z0-9_]/.test(source[i])) { id += source[i]; i++; }
      if (id === "true" || id === "false") tokens.push({ type: "Boolean", value: id, pos: i });
      else if (id === "null" || id === "undefined") tokens.push({ type: "Null", value: id, pos: i });
      else tokens.push({ type: "Identifier", value: id, pos: i });
      continue;
    }
    // Two-char ops
    const two = ch + next;
    if (["==","!=","<=",">=","&&","||"].includes(two)) {
      tokens.push({ type: two, value: two, pos: i }); i += 2; continue;
    }
    // Single-char
    const ops = {"+":"+","-":"-","*":"*","/":"/","%":"%","<":"<",">":">","!":"!","?":"?",":":":",".":".","(":"(",")":")",",":","};
    if (ops[ch]) { tokens.push({ type: ops[ch], value: ch, pos: i }); i++; continue; }
    i++; // skip unknown
  }
  tokens.push({ type: "EOF", value: "", pos: i });
  return tokens;
}

function parse(source) {
  const tokens = tokenize(source);
  let pos = 0;
  const peek = () => tokens[pos];
  const advance = () => tokens[pos++];
  const expect = (t) => { const tk = advance(); if (tk.type !== t) throw new Error(\`Expected \${t} got \${tk.type}\`); return tk; };

  function ternary() {
    let n = or(); if (peek().type === "?") { advance(); const c = ternary(); expect(":"); n = { k: "?", c: n, t: c, f: ternary() }; } return n;
  }
  function or() { let l = and(); while (peek().type === "||") { advance(); l = { k: "b", o: "||", l, r: and() }; } return l; }
  function and() { let l = eq(); while (peek().type === "&&") { advance(); l = { k: "b", o: "&&", l, r: eq() }; } return l; }
  function eq() { let l = cmp(); while (peek().type === "==" || peek().type === "!=") { const o = advance().value; l = { k: "b", o, l, r: cmp() }; } return l; }
  function cmp() { let l = add(); while (["<","<=",">",">="].includes(peek().type)) { const o = advance().value; l = { k: "b", o, l, r: add() }; } return l; }
  function add() { let l = mul(); while (peek().type === "+" || peek().type === "-") { const o = advance().value; l = { k: "b", o, l, r: mul() }; } return l; }
  function mul() { let l = unary(); while (peek().type === "*" || peek().type === "/" || peek().type === "%") { const o = advance().value; l = { k: "b", o, l, r: unary() }; } return l; }
  function unary() {
    if (peek().type === "!") { advance(); return { k: "u", o: "!", v: unary() }; }
    if (peek().type === "-") { advance(); return { k: "u", o: "-", v: unary() }; }
    return postfix();
  }
  function postfix() {
    let n = primary();
    while (peek().type === ".") { advance(); n = { k: "m", o: n, p: expect("Identifier").value }; }
    return n;
  }
  function primary() {
    const t = peek();
    if (t.type === "StateRef") { advance(); return { k: "s", p: t.value, r: t.value.split(".")[0] }; }
    if (t.type === "Number") { advance(); return { k: "l", v: parseFloat(t.value) }; }
    if (t.type === "String") { advance(); return { k: "l", v: t.value }; }
    if (t.type === "Boolean") { advance(); return { k: "l", v: t.value === "true" }; }
    if (t.type === "Null") { advance(); return { k: "l", v: null }; }
    if (t.type === "Identifier" && tokens[pos + 1]?.type === "(") {
      const name = advance().value; advance();
      const args = [];
      if (peek().type !== ")") { args.push(ternary()); while (peek().type === ",") { advance(); args.push(ternary()); } }
      expect(")"); return { k: "c", n: name, a: args };
    }
    if (t.type === "Identifier") { advance(); return { k: "s", p: t.value, r: t.value }; }
    if (t.type === "(") { advance(); const n = ternary(); expect(")"); return n; }
    advance(); return { k: "l", v: null };
  }
  return ternary();
}

function resolvePath(obj, path) {
  const parts = path.split(".");
  let cur = obj;
  for (const p of parts) {
    if (cur == null || typeof cur !== "object") return undefined;
    if (p === "__proto__" || p === "constructor" || p === "prototype") return undefined;
    cur = cur[p];
  }
  return cur;
}

const builtins = {
  min: (...a) => Math.min(...a.map(Number)),
  max: (...a) => Math.max(...a.map(Number)),
  abs: (n) => Math.abs(Number(n)),
  round: (n) => Math.round(Number(n)),
  floor: (n) => Math.floor(Number(n)),
  ceil: (n) => Math.ceil(Number(n)),
  length: (s) => Array.isArray(s) ? s.length : String(s).length,
  uppercase: (s) => String(s).toUpperCase(),
  lowercase: (s) => String(s).toLowerCase(),
  trim: (s) => String(s).trim(),
  includes: (s, q) => String(s).includes(String(q)),
  concat: (...a) => a.map(String).join(""),
  number: (v) => Number(v),
  string: (v) => String(v),
  boolean: (v) => Boolean(v),
  isNull: (v) => v == null,
  isArray: (v) => Array.isArray(v),
  count: (a) => Array.isArray(a) ? a.length : 0,
  first: (a) => Array.isArray(a) ? a[0] : undefined,
  last: (a) => Array.isArray(a) ? a[a.length - 1] : undefined,
  keys: (o) => o && typeof o === "object" ? Object.keys(o) : [],
  values: (o) => o && typeof o === "object" ? Object.values(o) : [],
  now: () => Date.now(),
  json: (v) => JSON.stringify(v),
  defaultTo: (v, d) => v ?? d,
};

function evaluate(node, ctx, depth = 0) {
  if (depth > MAX_DEPTH) throw new Error("Max expression depth");
  switch (node.k) {
    case "l": return node.v;
    case "s": return resolvePath(ctx, node.p);
    case "u": { const v = evaluate(node.v, ctx, depth + 1); return node.o === "!" ? !v : -Number(v); }
    case "b": {
      const l = evaluate(node.l, ctx, depth + 1);
      const r = evaluate(node.r, ctx, depth + 1);
      switch (node.o) {
        case "+": return typeof l === "string" || typeof r === "string" ? String(l) + String(r) : Number(l) + Number(r);
        case "-": return Number(l) - Number(r);
        case "*": return Number(l) * Number(r);
        case "/": { const d = Number(r); return d === 0 ? 0 : Number(l) / d; }
        case "%": { const d = Number(r); return d === 0 ? 0 : Number(l) % d; }
        case "==": return l == r;
        case "!=": return l != r;
        case "<": return Number(l) < Number(r);
        case "<=": return Number(l) <= Number(r);
        case ">": return Number(l) > Number(r);
        case ">=": return Number(l) >= Number(r);
        case "&&": return l && r;
        case "||": return l || r;
      }
      return undefined;
    }
    case "?": return evaluate(node.c, ctx, depth + 1) ? evaluate(node.t, ctx, depth + 1) : evaluate(node.f, ctx, depth + 1);
    case "m": { const o = evaluate(node.o, ctx, depth + 1); return o != null ? o[node.p] : undefined; }
    case "c": { const fn = builtins[node.n]; if (!fn) return undefined; return fn(...node.a.map(a => evaluate(a, ctx, depth + 1))); }
  }
}

function extractDeps(node) {
  const deps = new Set();
  function walk(n) {
    if (n.k === "s") deps.add(n.r);
    if (n.l) walk(n.l); if (n.r) walk(n.r);
    if (n.v) walk(n.v); if (n.c) walk(n.c);
    if (n.t) walk(n.t); if (n.f) walk(n.f);
    if (n.o && typeof n.o === "object") walk(n.o);
    if (n.a) n.a.forEach(walk);
  }
  walk(node);
  return deps;
}

export function evalExpr(source, context) {
  return evaluate(parse(source), context);
}

export function isExpression(value) {
  if (!value || typeof value !== "string") return false;
  return value.trim().startsWith("$");
}

// ── State Engine ──────────────────────────────────────────────

export class MintState {
  constructor() {
    this._values = {};
    this._subs = [];
    this._subId = 0;
    this._batch = 0;
    this._pending = new Set();
    this._undoStack = [];
    this._redoStack = [];
  }

  get(path) {
    const parts = path.split(".");
    let cur = this._values;
    for (const p of parts) {
      if (cur == null || typeof cur !== "object") return undefined;
      cur = cur[p];
    }
    return cur;
  }

  set(path, value) {
    this._saveUndo();
    this._setInternal(path, value);
    this._flush();
  }

  merge(path, partial) {
    const cur = this.get(path);
    this.set(path, typeof cur === "object" && cur ? { ...cur, ...partial } : partial);
  }

  batch(fn) {
    this._batch++;
    try { fn(); } finally { this._batch--; if (this._batch === 0) this._flush(); }
  }

  subscribe(path, cb) {
    const id = ++this._subId;
    this._subs.push({ id, path, cb });
    return () => { this._subs = this._subs.filter(s => s.id !== id); };
  }

  undo() {
    const snap = this._undoStack.pop();
    if (!snap) return false;
    this._redoStack.push(JSON.parse(JSON.stringify(this._values)));
    this._values = snap;
    this._notifyAll();
    return true;
  }

  redo() {
    const snap = this._redoStack.pop();
    if (!snap) return false;
    this._undoStack.push(JSON.parse(JSON.stringify(this._values)));
    this._values = snap;
    this._notifyAll();
    return true;
  }

  optimistic(path, value) {
    const prev = this.get(path);
    this._setInternal(path, value);
    this._flush();
    return {
      commit: () => {},
      rollback: () => { this._setInternal(path, prev); this._flush(); },
    };
  }

  getContext() { return { ...this._values }; }
  getAll() { return { ...this._values }; }

  init(defs) {
    for (const d of defs) {
      this._values[d.name] = d.defaultValue;
    }
  }

  _setInternal(path, value) {
    const parts = path.split(".");
    if (parts.length === 1) { this._values[parts[0]] = value; this._pending.add(parts[0]); return; }
    let cur = this._values;
    if (cur[parts[0]] == null || typeof cur[parts[0]] !== "object") cur[parts[0]] = {};
    cur = cur[parts[0]];
    for (let i = 1; i < parts.length - 1; i++) {
      if (cur[parts[i]] == null || typeof cur[parts[i]] !== "object") cur[parts[i]] = {};
      cur = cur[parts[i]];
    }
    cur[parts[parts.length - 1]] = value;
    this._pending.add(parts[0]);
  }

  _flush() {
    if (this._batch > 0) return;
    const changed = new Set(this._pending);
    this._pending.clear();
    for (const path of changed) {
      const value = this._values[path];
      for (const sub of this._subs) {
        if (sub.path === "" || sub.path === path || path.startsWith(sub.path + ".") || sub.path.startsWith(path + ".")) {
          try { sub.cb(this.get(sub.path || path), undefined); } catch {}
        }
      }
    }
  }

  _notifyAll() {
    for (const key of Object.keys(this._values)) this._pending.add(key);
    this._flush();
  }

  _saveUndo() {
    this._undoStack.push(JSON.parse(JSON.stringify(this._values)));
    if (this._undoStack.length > 50) this._undoStack.shift();
    this._redoStack = [];
  }
}

// ── Action Registry ───────────────────────────────────────────

export class MintActions {
  constructor(state) {
    this._state = state;
    this._handlers = {};
    this._schemas = {};
    this._middleware = [];
    this._registerBuiltins();
  }

  register(type, handler) { this._handlers[type] = handler; }
  registerSchemas(schemas) { for (const s of schemas) this._schemas[s.id] = s; }
  use(mw) { this._middleware.push(mw); }

  async dispatch(ref, ctx) {
    const schema = typeof ref === "string" ? this._schemas[ref] : this._schemas[ref?.actionId];
    if (!schema) return undefined;

    if (schema.condition) {
      try { if (!evalExpr(schema.condition, this._state.getContext())) return; } catch {}
    }

    const handler = this._handlers[schema.type];
    if (!handler) return undefined;

    const config = this._resolveConfig(schema.config || {});
    const fullCtx = { state: this._state, ...ctx };

    let idx = 0;
    const chain = this._middleware;
    const next = async () => {
      if (idx < chain.length) return chain[idx++](schema, fullCtx, next);
      return handler(config, fullCtx);
    };

    try {
      const result = await next();
      if (schema.onSuccess) for (const s of schema.onSuccess) await this.dispatch(s, ctx);
      return result;
    } catch (e) {
      if (schema.onError) for (const s of schema.onError) await this.dispatch(s, { ...ctx, error: e });
      throw e;
    }
  }

  _resolveConfig(config) {
    const ctx = this._state.getContext();
    const resolved = {};
    for (const [k, v] of Object.entries(config)) {
      if (typeof v === "string" && v.startsWith("$")) {
        try { resolved[k] = evalExpr(v, ctx); } catch { resolved[k] = v; }
      } else { resolved[k] = v; }
    }
    return resolved;
  }

  _registerBuiltins() {
    this.register("setState", (c) => this._state.set(String(c.path), c.value));
    this.register("resetState", (c) => this._state.set(String(c.path), c.defaultValue ?? null));
    this.register("navigate", (c, ctx) => ctx.navigation?.navigate(String(c.route), c.params));
    this.register("goBack", (_, ctx) => ctx.navigation?.goBack());
    this.register("toast", (c) => {
      const toasts = this._state.get("_toasts") || [];
      this._state.set("_toasts", [...toasts, { id: Date.now(), message: c.message, type: c.type || "info" }]);
    });
    this.register("openModal", (c) => this._state.set("_modals." + c.modalId, { open: true, data: c.data }));
    this.register("closeModal", (c) => this._state.set("_modals." + c.modalId, { open: false }));
    this.register("fetch", async (c) => {
      const url = _resolveUrl(c.url);
      const headers = _isAbsUrl(c.url) ? (c.headers || {}) : _authHeaders(c.headers);
      const res = await fetch(url, { method: c.method || "GET", headers, body: c.body ? JSON.stringify(c.body) : undefined });
      if (!res.ok) throw new Error("Request to " + url + " failed (" + res.status + ")" + (res.status === 401 ? " — set MINT_TOKEN or sign in" : ""));
      const data = await res.json().catch(() => null);
      if (c.storePath) this._state.set(String(c.storePath), data);
      return data;
    });
    this.register("mutate", async (c) => {
      const opt = this._state.optimistic(String(c.optimisticPath || c.storePath), c.optimisticValue);
      try { const r = await this._handlers.fetch(c, {}); opt.commit(); return r; }
      catch (e) { opt.rollback(); throw e; }
    });
    this.register("dbQuery", async (c) => {
      const base = _apiBase || "";
      const url = base + "/api/db/" + String(c.projectId || "");
      const res = await fetch(url, { method: "POST", headers: _authHeaders({ "Content-Type": "application/json" }), body: JSON.stringify({ sql: String(c.sql || ""), params: c.params || [] }) });
      const data = await res.json().catch(() => ({}));
      if (!res.ok || (data && data.error)) throw new Error((data && data.error) || ("DB query failed (" + res.status + ")"));
      const rows = Array.isArray(data.rows) ? data.rows : [];
      if (c.storePath) this._state.set(String(c.storePath), rows);
      return rows;
    });
    // ── CRUD writes ── nested value/where maps hold $expressions; resolve them
    // against state (top-level config resolution only handles $strings).
    const _resolveMap = (m) => {
      const out = {}; const ctx = this._state.getContext();
      for (const k in (m || {})) {
        const v = m[k];
        if (typeof v === "string" && v.charAt(0) === "$") { try { out[k] = evalExpr(v, ctx); } catch (e) { out[k] = v; } }
        else out[k] = v;
      }
      return out;
    };
    const _runDml = async (projectId, sql, params) => {
      const url = (_apiBase || "") + "/api/db/" + String(projectId || "");
      const res = await fetch(url, { method: "POST", headers: _authHeaders({ "Content-Type": "application/json" }), body: JSON.stringify({ sql: sql, params: params }) });
      const data = await res.json().catch(() => ({}));
      if (!res.ok || (data && data.error)) throw new Error((data && data.error) || ("DB write failed (" + res.status + ")"));
      return Array.isArray(data.rows) ? data.rows : [];
    };
    this.register("dbInsert", async (c) => {
      const values = _resolveMap(c.values); const cols = Object.keys(values);
      if (!c.table || !cols.length) return null;
      const sql = "INSERT INTO " + c.table + " (" + cols.map(function (x) { return '"' + x + '"'; }).join(", ") + ") VALUES (" + cols.map(function (_x, i) { return "$" + (i + 1); }).join(", ") + ") RETURNING *";
      const rows = await _runDml(c.projectId, sql, cols.map(function (x) { return values[x]; }));
      if (c.storePath) this._state.set(String(c.storePath), rows[0] || null);
      return rows[0] || null;
    });
    this.register("dbUpdate", async (c) => {
      const values = _resolveMap(c.values); const where = _resolveMap(c.where);
      const cols = Object.keys(values); const wcols = Object.keys(where);
      if (!c.table || !cols.length || !wcols.length) return null;
      const sets = cols.map(function (x, i) { return '"' + x + '" = $' + (i + 1); }).join(", ");
      const conds = wcols.map(function (x, i) { return '"' + x + '" = $' + (cols.length + i + 1); }).join(" AND ");
      const sql = "UPDATE " + c.table + " SET " + sets + " WHERE " + conds + " RETURNING *";
      const rows = await _runDml(c.projectId, sql, cols.map(function (x) { return values[x]; }).concat(wcols.map(function (x) { return where[x]; })));
      if (c.storePath) this._state.set(String(c.storePath), rows[0] || null);
      return rows[0] || null;
    });
    this.register("dbDelete", async (c) => {
      const where = _resolveMap(c.where); const wcols = Object.keys(where);
      if (!c.table || !wcols.length) return null;
      const conds = wcols.map(function (x, i) { return '"' + x + '" = $' + (i + 1); }).join(" AND ");
      const sql = "DELETE FROM " + c.table + " WHERE " + conds;
      await _runDml(c.projectId, sql, wcols.map(function (x) { return where[x]; }));
      return true;
    });
    this.register("condition", async (c, ctx) => {
      const result = evalExpr(String(c.expression), this._state.getContext());
      const branch = result ? c.then : c.else;
      if (branch && Array.isArray(branch)) for (const a of branch) await this.dispatch(a, ctx);
    });
    this.register("sequence", async (c, ctx) => { if (Array.isArray(c.actions)) for (const a of c.actions) await this.dispatch(a, ctx); });
    this.register("parallel", async (c, ctx) => { if (Array.isArray(c.actions)) await Promise.all(c.actions.map(a => this.dispatch(a, ctx))); });
    this.register("delay", (c) => new Promise(r => setTimeout(r, Number(c.ms || 1000))));
    this.register("openUrl", (c) => { if (typeof window !== "undefined") window.open(String(c.url), c.target || "_blank"); });

    // ── Auth (real endpoints; stores user + token in state) ──────
    const postJson = async (url, body) => {
      const target = _resolveUrl(url);
      const res = await fetch(target, { method: "POST", headers: _authHeaders({ "Content-Type": "application/json" }), body: JSON.stringify(body) });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error((data && data.error) || ("Auth request to " + target + " failed (" + res.status + ")"));
      return data;
    };
    const storeSession = (c, data) => {
      if (data.user !== undefined) this._state.set(String(c.userPath || "user"), data.user);
      if (data.token !== undefined) this._state.set(String(c.tokenPath || "session.token"), data.token);
      _persistSession(data.user, data.token);
    };
    this.register("signIn", async (c) => {
      const data = await postJson(String(c.url || "/api/login"), { email: c.email, password: c.password });
      storeSession(c, data); return data;
    });
    this.register("signUp", async (c) => {
      const body = c.body || { email: c.email, password: c.password, name: c.name };
      const data = await postJson(String(c.url || "/api/signup"), body);
      storeSession(c, data); return data;
    });
    this.register("signOut", async (c) => {
      try { await fetch(String(c.url || "/api/logout"), { method: "POST" }); } catch (e) {}
      this._state.set(String(c.userPath || "user"), null);
      this._state.set(String(c.tokenPath || "session.token"), null);
      _clearSession();
    });
  }

  destroy() {}
}

// ── Binding Engine ────────────────────────────────────────────

export class MintBindings {
  constructor(state) {
    this._state = state;
    this._compiled = {};
    this._subs = {};
  }

  compile(componentId, bindings, conditionalRender) {
    const compiled = {};
    if (bindings) {
      for (const [prop, expr] of Object.entries(bindings)) {
        try { compiled[prop] = parse(expr); } catch {}
      }
    }
    if (conditionalRender) {
      try { compiled.__visible = parse(conditionalRender); } catch {}
    }
    this._compiled[componentId] = compiled;
  }

  resolve(componentId, staticProps = {}) {
    const bindings = this._compiled[componentId];
    if (!bindings) return { ...staticProps };
    const ctx = this._state.getContext();
    const result = { ...staticProps };
    for (const [prop, ast] of Object.entries(bindings)) {
      try { result[prop] = evaluate(ast, ctx); } catch {}
    }
    return result;
  }

  isVisible(componentId) {
    const bindings = this._compiled[componentId];
    if (!bindings?.__visible) return true;
    try { return Boolean(evaluate(bindings.__visible, this._state.getContext())); } catch { return true; }
  }

  subscribe(componentId, onChange) {
    const bindings = this._compiled[componentId];
    if (!bindings) return () => {};
    const deps = new Set();
    for (const ast of Object.values(bindings)) extractDeps(ast).forEach(d => deps.add(d));
    const unsubs = [];
    for (const dep of deps) {
      unsubs.push(this._state.subscribe(dep, () => onChange(this.resolve(componentId))));
    }
    this._subs[componentId] = unsubs;
    return () => { (this._subs[componentId] || []).forEach(u => u()); delete this._subs[componentId]; };
  }

  createTwoWayHandler(expression) {
    const path = expression.startsWith("$") ? expression.slice(1) : expression;
    return (value) => this._state.set(path, value);
  }

  destroy() {
    for (const unsubs of Object.values(this._subs)) unsubs.forEach(u => u());
    this._subs = {};
    this._compiled = {};
  }
}

// ── Workflow Engine ───────────────────────────────────────────

export class MintWorkflows {
  constructor(state, actions) {
    this._state = state;
    this._actions = actions;
    this._executors = {};
    this._registerBuiltins();
  }

  registerExecutor(type, fn) { this._executors[type] = fn; }

  async execute(workflow, input) {
    const start = Date.now();
    const trace = [];
    const vars = { _input: input };

    // Find entry nodes (no incoming edges)
    const hasIncoming = new Set();
    for (const e of workflow.edges || []) hasIncoming.add(e.to);
    const entries = (workflow.nodes || []).filter(n => !hasIncoming.has(n.id)).map(n => n.id);
    if (!entries.length) return { success: false, trace, duration: 0, error: "No entry nodes" };

    const completed = new Set();
    const nodeMap = {};
    for (const n of workflow.nodes || []) nodeMap[n.id] = n;

    const edgesFrom = {};
    const edgesTo = {};
    for (const n of workflow.nodes || []) { edgesFrom[n.id] = []; edgesTo[n.id] = []; }
    for (const e of workflow.edges || []) { (edgesFrom[e.from] || []).push(e); (edgesTo[e.to] || []).push(e); }

    let lastOutput = input;

    const exec = async (nodeId) => {
      if (completed.has(nodeId)) return vars["_node_" + nodeId];
      const node = nodeMap[nodeId];
      if (!node) throw new Error("Node not found: " + nodeId);

      // Wait for dependencies
      for (const e of edgesTo[nodeId] || []) {
        if (!completed.has(e.from)) await exec(e.from);
        // Check edge condition
        if (e.condition) {
          try {
            const ctx = { ...this._state.getContext(), ...vars };
            if (!evalExpr(e.condition, ctx)) {
              trace.push({ nodeId, type: node.type, status: "skipped", duration: 0 });
              completed.add(nodeId);
              return undefined;
            }
          } catch {}
        }
      }

      const t = { nodeId, type: node.type, label: node.label, status: "running", start: Date.now() };
      trace.push(t);

      const retry = node.retryPolicy || { maxRetries: 0, delayMs: 1000, backoff: "linear" };
      let lastErr = null;

      for (let attempt = 0; attempt <= retry.maxRetries; attempt++) {
        try {
          const executor = this._executors[node.type];
          if (!executor) throw new Error("No executor for: " + node.type);

          const output = await Promise.race([
            executor(node, { state: this._state, actions: this._actions, vars, input }),
            new Promise((_, rej) => setTimeout(() => rej(new Error("Timeout")), 30000))
          ]);

          vars["_node_" + nodeId] = output;
          lastOutput = output;
          t.status = "success"; t.output = output; t.duration = Date.now() - t.start;
          completed.add(nodeId);

          // Execute outgoing edges
          for (const e of edgesFrom[nodeId] || []) await exec(e.to);
          return output;
        } catch (e) {
          lastErr = e;
          if (attempt < retry.maxRetries) {
            const delay = retry.backoff === "exponential" ? retry.delayMs * Math.pow(2, attempt) : retry.delayMs * (attempt + 1);
            await new Promise(r => setTimeout(r, delay));
          }
        }
      }

      t.status = "failed"; t.error = lastErr?.message; t.duration = Date.now() - t.start;
      completed.add(nodeId);
      throw lastErr;
    };

    try {
      for (const id of entries) await exec(id);
      return { success: true, workflowId: workflow.id, output: lastOutput, trace, duration: Date.now() - start };
    } catch (e) {
      return { success: false, workflowId: workflow.id, output: null, trace, duration: Date.now() - start, error: e?.message };
    }
  }

  _resolveTemplate(template, vars) {
    return template.replace(/\\{\\{(.+?)\\}\\}/g, (_, expr) => {
      try {
        const ctx = { ...this._state.getContext(), ...vars };
        return String(evalExpr(expr.trim(), ctx) ?? "");
      } catch { return "{{" + expr + "}}"; }
    });
  }

  _registerBuiltins() {
    this.registerExecutor("condition", async (node, ctx) => {
      return evalExpr(String(node.config?.expression || "true"), { ...ctx.state.getContext(), ...ctx.vars });
    });
    this.registerExecutor("transform", async (node, ctx) => {
      const result = evalExpr(String(node.config?.expression || "$_input"), { ...ctx.state.getContext(), ...ctx.vars });
      if (node.config?.storePath) ctx.state.set(String(node.config.storePath), result);
      return result;
    });
    this.registerExecutor("delay", async (node) => {
      await new Promise(r => setTimeout(r, Number(node.config?.ms || 1000)));
    });
    this.registerExecutor("apiCall", async (node, ctx) => {
      const url = this._resolveTemplate(String(node.config?.url || ""), ctx.vars);
      const method = String(node.config?.method || "GET");
      const res = await fetch(url, {
        method,
        headers: node.config?.headers || {},
        body: node.config?.body ? JSON.stringify(node.config.body) : undefined,
      });
      const data = await res.json();
      if (node.config?.storePath) ctx.state.set(String(node.config.storePath), data);
      return data;
    });
    this.registerExecutor("updateState", async (node, ctx) => {
      const path = String(node.config?.path || "");
      let value = node.config?.value;
      if (typeof value === "string" && value.startsWith("$")) {
        value = evalExpr(value, { ...ctx.state.getContext(), ...ctx.vars });
      }
      ctx.state.set(path, value);
      return { path, value };
    });
    this.registerExecutor("navigate", async (node, ctx) => {
      ctx.navigation?.navigate(String(node.config?.route || "/"));
    });
    this.registerExecutor("toast", async (node, ctx) => {
      const msg = this._resolveTemplate(String(node.config?.message || ""), ctx.vars);
      const toasts = ctx.state.get("_toasts") || [];
      ctx.state.set("_toasts", [...toasts, { id: Date.now(), message: msg, type: node.config?.type || "info" }]);
    });
    this.registerExecutor("logger", async (node, ctx) => {
      console.log("[Workflow]", this._resolveTemplate(String(node.config?.message || ""), ctx.vars));
    });
    this.registerExecutor("loop", async (node, ctx) => {
      const items = evalExpr(String(node.config?.items || "[]"), { ...ctx.state.getContext(), ...ctx.vars });
      if (!Array.isArray(items)) return [];
      const results = [];
      for (let i = 0; i < items.length; i++) {
        ctx.vars._loop = { item: items[i], index: i };
        if (node.config?.actions) {
          for (const a of node.config.actions) results.push(await ctx.actions.dispatch(a, {}));
        }
      }
      delete ctx.vars._loop;
      return results;
    });
    this.registerExecutor("parallel", async (node, ctx) => {
      if (!node.config?.actions) return [];
      return Promise.all(node.config.actions.map(a => ctx.actions.dispatch(a, {})));
    });
  }

  destroy() {}
}

// ── Factory ───────────────────────────────────────────────────

export function createMintRuntime(schema) {
  const state = new MintState();
  if (schema?.globalState) state.init(schema.globalState);
  if (schema?.screens) {
    for (const screen of schema.screens) {
      if (screen.localState) state.init(screen.localState);
    }
  }

  const actions = new MintActions(state);
  if (schema?.globalActions) actions.registerSchemas(schema.globalActions);
  if (schema?.screens) {
    for (const screen of schema.screens) {
      if (screen.actions) actions.registerSchemas(screen.actions);
    }
  }

  const bindings = new MintBindings(state);
  if (schema?.screens) {
    for (const screen of schema.screens) {
      const compileAll = (components) => {
        for (const comp of components || []) {
          bindings.compile(comp.id, comp.bindings, comp.conditionalRender);
          if (comp.children) compileAll(comp.children);
        }
      };
      compileAll(screen.components);
    }
  }

  const workflows = new MintWorkflows(state, actions);

  // Database client (if schema has database config)
  let db = null;
  if (schema?.database) {
    db = new MintDB(schema.database);
  }

  return {
    state,
    actions,
    bindings,
    workflows,
    db,
    evalExpr,
    isExpression,
    executeWorkflow: (workflow, input) => workflows.execute(workflow, input),
    destroy: () => { state._subs = []; actions.destroy(); bindings.destroy(); workflows.destroy(); },
  };
}

// ── Database Client ───────────────────────────────────────────

export class MintDB {
  constructor(config) {
    this._baseUrl = config.connectionUrl || (_apiBase ? _apiBase + "/api/mint-db" : "https://api.mintit.pro/api/mint-db");
    this._apiKey = config.apiKey || _authToken || "";
    this._tables = {};
    if (config.tables) {
      for (const t of config.tables) this._tables[t.name] = t;
    }
  }

  async query(sql, params = []) {
    const res = await fetch(this._baseUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(this._apiKey ? { Authorization: "Bearer " + this._apiKey } : {}),
      },
      body: JSON.stringify({ text: sql, params }),
    });
    if (!res.ok) throw new Error("DB query to " + this._baseUrl + " failed (" + res.status + ")" + (res.status === 401 ? " — set MINT_TOKEN" : ""));
    return res.json();
  }

  async findAll(table, options = {}) {
    const { where = {}, orderBy = "created_at", order = "DESC", limit = 50, offset = 0 } = options;
    const params = [];
    const wheres = [];
    const t = this._tables[table];
    if (t?.softDelete) wheres.push('"deleted_at" IS NULL');
    for (const [k, v] of Object.entries(where)) {
      params.push(v);
      wheres.push('"' + k + '" = $' + params.length);
    }
    let sql = 'SELECT * FROM "' + table + '"';
    if (wheres.length) sql += " WHERE " + wheres.join(" AND ");
    sql += ' ORDER BY "' + orderBy + '" ' + order;
    params.push(limit); sql += " LIMIT $" + params.length;
    params.push(offset); sql += " OFFSET $" + params.length;
    return this.query(sql, params);
  }

  async findById(table, id) {
    const t = this._tables[table];
    const sd = t?.softDelete ? ' AND "deleted_at" IS NULL' : "";
    return this.query('SELECT * FROM "' + table + '" WHERE "id" = $1' + sd, [id])
      .then(r => r.rows?.[0] || null);
  }

  async create(table, data) {
    const keys = Object.keys(data).filter(k => k !== "id");
    const params = keys.map(k => data[k]);
    const cols = keys.map(k => '"' + k + '"').join(", ");
    const vals = keys.map((_, i) => "$" + (i + 1)).join(", ");
    return this.query('INSERT INTO "' + table + '" (' + cols + ') VALUES (' + vals + ') RETURNING *', params)
      .then(r => r.rows?.[0]);
  }

  async update(table, id, data) {
    const keys = Object.keys(data).filter(k => k !== "id");
    const params = [id];
    const sets = keys.map(k => { params.push(data[k]); return '"' + k + '" = $' + params.length; });
    return this.query('UPDATE "' + table + '" SET ' + sets.join(", ") + ' WHERE "id" = $1 RETURNING *', params)
      .then(r => r.rows?.[0]);
  }

  async remove(table, id) {
    const t = this._tables[table];
    if (t?.softDelete) {
      return this.query('UPDATE "' + table + '" SET "deleted_at" = now() WHERE "id" = $1 RETURNING *', [id])
        .then(r => r.rows?.[0]);
    }
    return this.query('DELETE FROM "' + table + '" WHERE "id" = $1 RETURNING *', [id])
      .then(r => r.rows?.[0]);
  }

  async count(table, where = {}) {
    const params = [];
    const wheres = [];
    const t = this._tables[table];
    if (t?.softDelete) wheres.push('"deleted_at" IS NULL');
    for (const [k, v] of Object.entries(where)) {
      params.push(v);
      wheres.push('"' + k + '" = $' + params.length);
    }
    let sql = 'SELECT COUNT(*) as count FROM "' + table + '"';
    if (wheres.length) sql += " WHERE " + wheres.join(" AND ");
    return this.query(sql, params).then(r => Number(r.rows?.[0]?.count || 0));
  }
}

// ── Auth Guard ────────────────────────────────────────────────

export class MintAuthGuard {
  constructor(state, config = {}) {
    this._state = state;
    this._userPath = config.userStatePath || "user";
    this._roleField = config.roleField || "role";
    this._loginRoute = config.loginRoute || "/login";
  }

  _getUser() {
    const u = this._state.get(this._userPath);
    if (!u || typeof u !== "object" || !u.id) return null;
    return u;
  }

  getUserRole() { const u = this._getUser(); return u ? String(u[this._roleField] || "") : null; }
  isAuthenticated() { return this._getUser() !== null; }

  hasRole(roles) {
    if (!roles || !roles.length) return true;
    const r = this.getUserRole();
    return r ? roles.indexOf(r) >= 0 : false;
  }

  checkRouteAccess(route) {
    if (route.auth && !this.isAuthenticated()) return { allowed: false, reason: "unauthenticated", redirectTo: this._loginRoute };
    if (route.roles && route.roles.length) {
      if (!this.isAuthenticated()) return { allowed: false, reason: "unauthenticated", redirectTo: this._loginRoute };
      if (!this.hasRole(route.roles)) return { allowed: false, reason: "insufficient_role", redirectTo: this._loginRoute };
    }
    return { allowed: true };
  }

  checkComponentAccess(comp) {
    if (!comp.requiredRoles || !comp.requiredRoles.length) return true;
    return this.hasRole(comp.requiredRoles);
  }
}

// ── Data Table Engine ─────────────────────────────────────────

export class MintDataTable {
  constructor(config) {
    this._config = config;
    this._page = 1;
    this._pageSize = (config.pagination && config.pagination.pageSize) || 10;
    this._sortKey = (config.defaultSort && config.defaultSort.key) || null;
    this._sortDir = (config.defaultSort && config.defaultSort.direction) || "asc";
    this._search = "";
    this._filters = {};
  }

  process(data) {
    var rows = data.slice();
    // Search
    if (this._search && this._config.searchable) {
      var q = this._search.toLowerCase();
      var fields = this._config.searchFields || this._config.columns.map(function(c) { return c.key; });
      rows = rows.filter(function(row) {
        return fields.some(function(f) { var v = row[f]; return v != null && String(v).toLowerCase().indexOf(q) >= 0; });
      });
    }
    // Filters
    for (var fk in this._filters) {
      var fv = this._filters[fk];
      if (fv == null || fv === "" || fv === "all") continue;
      rows = rows.filter(function(row) { return String(row[fk]) === String(fv); });
    }
    var totalRows = rows.length;
    // Sort
    if (this._sortKey) {
      var key = this._sortKey, dir = this._sortDir === "asc" ? 1 : -1;
      var col = this._config.columns.find(function(c) { return c.key === key; });
      rows.sort(function(a, b) {
        var av = a[key], bv = b[key];
        if (av == null && bv == null) return 0;
        if (av == null) return dir;
        if (bv == null) return -dir;
        if (col && (col.type === "number" || col.type === "currency")) return (Number(av) - Number(bv)) * dir;
        return String(av).localeCompare(String(bv)) * dir;
      });
    }
    // Paginate
    var ps = this._pageSize, tp = Math.max(1, Math.ceil(totalRows / ps));
    var pg = Math.min(this._page, tp), start = (pg - 1) * ps;
    var paged = this._config.pagination && this._config.pagination.enabled ? rows.slice(start, start + ps) : rows;
    return { rows: paged, totalRows: totalRows, totalPages: tp, currentPage: pg, pageSize: ps, hasNext: pg < tp, hasPrev: pg > 1 };
  }

  setPage(p) { this._page = Math.max(1, p); }
  setPageSize(s) { this._pageSize = s; this._page = 1; }
  setSort(k) { if (this._sortKey === k) { this._sortDir = this._sortDir === "asc" ? "desc" : "asc"; } else { this._sortKey = k; this._sortDir = "asc"; } this._page = 1; }
  setSearch(q) { this._search = q; this._page = 1; }
  setFilter(col, val) { this._filters[col] = val; this._page = 1; }
  clearFilters() { this._filters = {}; this._search = ""; this._page = 1; }
}

// ── Timeline Engine ───────────────────────────────────────────

export function processTimeline(data, config, activeStepValue) {
  var activeIndex = -1;
  var items = data.map(function(row, index) {
    var title = String(row[config.titleKey] || "");
    var subtitle = config.subtitleKey ? String(row[config.subtitleKey] || "") : undefined;
    var timestamp = config.timestampKey ? row[config.timestampKey] : undefined;
    var comment = config.commentKey ? String(row[config.commentKey] || "") : undefined;
    var status = "pending";
    if (activeStepValue != null && config.activeMatchKey) {
      if (row[config.activeMatchKey] === activeStepValue) { status = "active"; activeIndex = index; }
      else if (activeIndex >= 0) { status = "pending"; }
      else { status = "completed"; }
    } else if (config.statusKey) {
      var s = String(row[config.statusKey] || "").toLowerCase();
      if (["completed","done","approved","reimbursed","success"].indexOf(s) >= 0) status = "completed";
      else if (["active","running","current","pending_manager","pending_finance"].indexOf(s) >= 0) status = "active";
      else if (["failed","error","rejected"].indexOf(s) >= 0) status = "failed";
      else if (["skipped","cancelled"].indexOf(s) >= 0) status = "skipped";
    } else { status = "completed"; }
    return { key: String(row.id || row.step_key || index), title: title, subtitle: subtitle, timestamp: timestamp, comment: comment && comment !== "undefined" ? comment : undefined, status: status, raw: row };
  });
  return { items: items, activeIndex: activeIndex, totalSteps: items.length, completedSteps: items.filter(function(i) { return i.status === "completed"; }).length };
}

// ── Status Chip ───────────────────────────────────────────────

export var STATUS_COLORS = {
  draft: "#6B7280", pending_manager: "#F59E0B", pending_department_head: "#F59E0B",
  pending_finance: "#3B82F6", approved: "#10B981", rejected: "#EF4444",
  changes_requested: "#F97316", reimbursed: "#8B5CF6", active: "#3B82F6",
  completed: "#10B981", success: "#10B981", warning: "#F59E0B",
  error: "#EF4444", info: "#3B82F6", default: "#6B7280"
};

export var STATUS_LABELS = {
  draft: "Draft", pending_manager: "Pending Manager", pending_department_head: "Pending Dept Head",
  pending_finance: "Pending Finance", approved: "Approved", rejected: "Rejected",
  changes_requested: "Changes Requested", reimbursed: "Reimbursed",
  active: "Active", completed: "Completed"
};

export function getStatusColor(status) { return STATUS_COLORS[status] || STATUS_COLORS.default; }
export function getStatusLabel(status) { return STATUS_LABELS[status] || status.replace(/_/g, " ").replace(/\\b\\w/g, function(l) { return l.toUpperCase(); }); }
`;
}

